### ISSUE TITLE
collections type error in iterators.py

### ISSUE THREAD

**Issue by rjhornsby** [gchamon/sysrsync#15]
Running Python 3.10.0 in a venv, on macOS 11.5.

When using the option `exclusions=`, I'm hitting a problem in helpers/iterators.py:

```
def flatten(input_iter: Iterable[Any]) -> List[Any]:
    list_of_lists = (element if isinstance(element, collections.Iterable)
```

Specifically, it's throwing [this error](https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7/53978543#53978543):

```
  File "/Users/rhornsby/projects/python/rs_media_sync/.venv/lib/python3.10/site-packages/sysrsync/helpers/iterators.py", line 8, in <genexpr>
    list_of_lists = (element if isinstance(element, collections.Iterable)
AttributeError: module 'collections' has no attribute 'Iterable'
```

As far as I can tell, this is because the collections type at some point changed to be `collections.abc.Iterable` (`abc` here is literal). 

I ran into a second issue that might be my ignorance while trying to fix this. After cloning sysrsync, while trying to install the dependencies with `pip3 install -r requirements.txt`, it fails here:

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.7.4 from https://files.pythonhosted.org/packages/05/e4/baf0031e39cf545f0c9edd5b1a2ea12609b7fcba2d58e118b11753d68cf0/typing_extensions-4.0.1-py3-none-any.whl#sha256=7f001e5ac290a0c0401508864c7ec868be4e701886d5b573a9528ed3973d9d3b (from mypy==0.812->-r requirements.txt (line 48))
```

I think this this is because `mypy` doesn't specify hashes in _its_ [requirements](https://github.com/python/mypy/blob/master/mypy-requirements.txt), where it depends on `typing_extensions`? I'm not sure how to disable the `require-hashes` or somehow otherwise fix it to get past this to be able to make, test, and submit a PR for sysrsync.

**Comment by gchamon** [comment]
Sorry for the long wait.
These two problems were relatively simple to solve: add typed-ast to pyproject.toml and regenerate requirements.txt, and inspect `collections` using `dir` and import `Iterables` appropriately.

However, I just found out `nose` is no longer maintained, so all tests are busted in python 3.10 :/
So much for trying a nice test framework. There are instructions to migrate to `nose2` but I guess I will just take the safer road and port the tests to `unittest` which is sure to be maintained as long as python is.

**Comment by rjhornsby** [comment]
It looks like this fixed the collections issue. Thanks for doing that!
