### ISSUE TITLE
Missing Rsync options

### ISSUE THREAD

**Issue by ullix** [gchamon/sysrsync#30]
Am I not seeing it, or does this wrapper not have the rsync option "inclusion" available? "exclusion" seems to be working, but attempting inclusion in the same approach results in "TypeError: get_rsync_command() got an unexpected keyword argument 'inclusion'"?

An how do I add rsync options like "--numeric-ids"?

Can I define "--log-file" and "--link-dest"?

**Comment by gchamon** [comment]
Have you tried using the `options` argument? It is supposed to expose the rest of the flags available in rsync. If you tried that and encountered problems, please feel free to report them.

**Comment by ullix** [comment]
I don't know whether all the options from rsync can be covered by the options-argument in your code, but it seems strange to expect to cover "inclusion" among options. You do have a separate "exclusion" already, so why treat inclusion differently?

Trying it anyway with this code:
```
    sysrsync.run(   source      = zip_log,
                    destination = bupDest,
                    options = [rsyncOpts, "--numeric-ids", '--inclusion=["*.txt", "*.tzip"]'],
                    exclusions=["*.mp4", "*.mp3", "backup.bup"],
                    )
```
results in:
```
raise RsyncError(f"[sysrsync runner] {action} exited with code {return_code}")
sysrsync.exceptions.RsyncError: [sysrsync runner] rsync -Cavv --numeric-ids --inclusion=["*.txt", "*.tzip"] locallog/_2022-11-16_10-11-34-277770_transfer.log.zip /home/BackupLocal/BackusoTEST/2022-11-16_10:11:34-277770 --exclude *.mp4 --exclude *.mp3 --exclude backup.bup exited with code 1
```
Whatever this means, I have no idea.

**Comment by gchamon** [comment]
@ullix this means that rsync call exited with code 1.

That inclusion syntax doesn't seem right to me. Let's say you have the following structure:

```
lt /tmp/foo
 foo
├──  a
├──  b
└──  c
```

If you want to send a and b but exclude c using inclusion, you would do so by calling `rsync -va --include={'a','b'} --exclude='*' /tmp/foo/ /tmp/bar` (I understand exclude and include are redundant, but this is just for illustration).

So I believe the correct call for sysrsync would be:

```python
    sysrsync.run(   source      = zip_log,
                    destination = bupDest,
                    options = [rsyncOpts, "--numeric-ids", '--include={"*.txt","*.tzip"}'],
                    exclusions=["*.mp4", "*.mp3", "backup.bup"],
                    )
```

As for the exception itself, it is masking the original exception from subprocess. I guess we could expose the original exception to make things clearer, but it would be a breaking change. I don't know if I would want to break the exception API right now. Another option would be to populate a global exception object, similar to what flask does with `flask.request`.

You can however, get the command using `sysrsync.get_rsync_command` and pass it yourself to `subprocess.run`, this would expose you to the original subprocess exception.

As for why I didn't expose `include` with `exclude`, although it would make sense for the sake of symmetry, it would also be over-engineering the API before I would actually need it. I would be happy to accept a pull request for it though, as it seems like you hit a use case that needs it.

**Comment by ullix** [comment]
> I understand exclude and include are redundant, 
Not really. May be used not so often, but is standard to include some fraction of what you previously excluded.

But you want/need curly braces when using inclusive? Doesn't this strike you as odd when you compare this with exclusive? rsync has soooo many options, and now I also need to know which one needs different handling?

In my own use of rsync I simply use a `subprocess.Popen(command, ...)`, where command is constructed from a list() of items via format(). Perhaps clumsy but simple and consistent. I think I stay with that, thanks.

**Comment by gchamon** [comment]
You said it yourself, rsync has many options, and dealing with each on the API level isn't the purpose of the project. This is why options exist.

You don't need curly braces, those are as I explained shell expansion. Just use --include=pattern for each pattern you have. It is as simple as `options=[*rsyncOpts, *[f"--include='{pattern}'" for pattern in ("*.txt", "*.tzip")]]`.

**Comment by gchamon** [comment]
Closing as this isssue is out of the scope of the project
