### ISSUE TITLE
Bug:  strict_host_key_checking False is ignored 

### ISSUE THREAD

**Issue by stevehenderson** [gchamon/sysrsync#31]
# Issue

Setting `strict_host_key_checking` to false is ignored if you do not either specify `private_key` or `rsh_port`
This can occur in the following usecase: `sysrsync` is called by an application ran as a user who already has a preconfigured `private_key` specified in their `ssh` environment.

# Replication

Prep environment:

Assumption: the user has a `private_key` in their `~/.ssh` folder (e.g. `id_rsa`)

```
mkdir /tmp/in
mkdir /tmp/out
echo "hello" >> /tmp/in/test.txt
ssh-keygen -R 127.0.0.1
```

Run the following:

```
import sysrsync

sysrsync.run(source="/tmp/in",source_ssh="127.0.0.1",options=['-a'],strict_host_key_checking=False, destination="/tmp/out")
                  
```

Will yield something like this:

```
python rsync_check.py 
The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
ED25519 key fingerprint is SHA256:6a26OyQqLw5USUetuC/3aKO36/JxE4jK1NHNbDmXGIQ.
This host key is known by the following other names/addresses:
    .
    .
    .
Are you sure you want to continue connecting (yes/no/[fingerprint])?  ssh-keygen -R localhost
```

## Cause

The following check in `sysrsync/command_maker.py` will not return true (and thus return an empty options list) if the `strict_host_key_checking` value equals `False` and `private_key` and `rsh_port` are not specified:

```
if any((private_key, rsh_port, strict_host_key_checking))
```

## Solution

[PR 32 Submitted](https://github.com/gchamon/sysrsync/pull/32)

**Comment by gchamon** [comment]
Hey there!

Thanks for this Issue/PR! I am aware of it and will soon be on reviewing and merging it!

Just gotta deal with life, and the end of the year (christmas + new years) is always a bit chaotic.

Thanks for the patience.

Merry xmas and a happy new year!
