### ISSUE TITLE
Missing Releases on GitHub

### ISSUE THREAD

**Issue by LevN0** [gchamon/sysrsync#4]
Looks like a great project.

Noticed that Releases on GitHub only have 0.1.2, but PyPi has 0.2.1.

**Comment by gchamon** [comment]
I started using python poetry directly to manage deploys and version bumps. I think I have to manually sync poetry and github releases.

Do you happen to know a way to automate the release workflow using poetry?

**Comment by gchamon** [comment]
@LevN0 for now I have updated the release on github to match that of PyPI, released with poetry

I have a somewhat loose release process, since I work alone, but I could use some opinions on how to manage it, now that more people is showing interest in the project

**Comment by LevN0** [comment]
I have never used poetry, so unfortunately not able to make a suggestion there. 

There seem to be a few different ways of automating GitHub releases. Circle CI has a [page](https://circleci.com/blog/publishing-to-github-releases-via-circleci/) describing at least a couple methods that are viable with CI/CD. [Travis CI](https://docs.travis-ci.com/user/deployment/releases/) seems to have a built-in mechanism.

Here are a couple more options, [1](https://github.com/marketplace/actions/automatic-releases), [2](https://github.com/marketplace/actions/automatic-releases). I have never automated a GitHub release to be honest. If I wanted to automate it, I would probably be most inclined to use the CI/CD method since it can also run tests cross platform and it seems like adding GitHub release would be -fairly- straight forward and in your case could possibly also trigger poetry to make PyPi release.
