### ISSUE TITLE
get_rsync_command tries to connect via SSH

### ISSUE THREAD

**Issue by LevN0** [gchamon/sysrsync#5]
Probably a public API titled `get_rsync_command` should not remotely connect to another machine to generate the command.

This is unnecessarily called even when sync_source_contents if False, because there is no guard on [this statement](https://github.com/gchamon/sysrsync/blob/793d164d0c70e2d22f29c8eef448b9aafeb39879/sysrsync/command_maker.py#L23). Easy fix on that though.

**Comment by gchamon** [comment]
Nice catch. I will first of all write a test to cover this case.

There could also be an option to disable remote file verification if the user won't need this verification in time of command generation. Could be useful in a situation where you locally don't have access to the machines but later, using a Bastion, do.

What do you think?

**Comment by LevN0** [comment]
I would have avoided modifying the native rsync behavior. If you think it should be present, I recommend adding a None option to sync_source_contents, which preserves native rsync behavior.

**Comment by gchamon** [comment]
I will remove this check, run the command and check for rsync error. If it has "No such file or directory" in it, I will raise a `NoSuchFileOrDirectory` custom exception, else, will keep raising `RsyncError`. Maybe rename it to `UnknownRsyncError`
