### ISSUE TITLE
Add private key option

### ISSUE THREAD

**Issue by diamkil** [gchamon/sysrsync#7]
Add option to use a private key

**Comment by gchamon** [comment]
Hey! Thanks for the idea!

I can see why adding an argument for private keys could be useful, but you can also achieve the same result using the `options` argument:

 ```python
import os
key_file = os.path.join(os.path.expanduser("~/.ssh"), "totally_secret_key.pem"))

sysrsync.run(source='/home/user/files',
             destination='/home/server/files',
             destination_ssh='user@192.168.0.100',
             options=['-a', '-i', key_file])
```

you can also have on your `~/.ssh/config`:
```
host remote-server
 HostName 192.168.0.100
 User user
 IdentityFile ~/.ssh/totally_secret_key.pem
```

And use it so in the python code:
```python
sysrsync.run(source='/home/user/files',
             destination='/home/server/files',
             destination_ssh='remote-server')
```

If you feel like it still warrants a new argument for a key file I am open to discuss it further.

**Comment by diamkil** [comment]
Doesn't seem to work
<img width="1407" alt="Screen Shot 2021-09-11 at 16 18 32" src="https://user-images.githubusercontent.com/35732047/132960653-ef2f9f3f-524c-4c83-b875-50507d637e81.png">

**Comment by gchamon** [comment]
Can you run the command that was printed along the error message using bash?

**Comment by diamkil** [comment]
I did, -i isn't the private key option for rsync, there isn't one you need to use -e "ssh -i (key)" as a rsync argument for it to work

**Comment by diamkil** [comment]
Welp even typed all by hand it doesn't work using sysrsync, ran the command sysrsync tried directly in my command line and it worked there
<img width="1350" alt="Screen Shot 2021-09-11 at 19 33 06" src="https://user-images.githubusercontent.com/35732047/132965985-2ebab89d-c07b-4203-80f3-eb6cacfb967d.png">

**Comment by diamkil** [comment]
Hi @gchamon, I'm currently testing the feature and it doesn't seem to work no matter what I try
<img width="1381" alt="Screen Shot 2021-09-15 at 13 41 40" src="https://user-images.githubusercontent.com/35732047/133482897-32c8de88-9792-4d79-b47a-37ae2f7eeef2.png">
